spring:
  profiles: default
  datasource:
    url: "jdbc:sqlite:/Users/halilural/Documents/development/SapCloud/CAP/java/products-service/products-service/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never
    hikari:
      maximum-pool-size: 1
      
      
      
